# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df81556badedfd0aa6d78144d774c97674f739d71e193d4c27bc2bdbf761846df7e086f39a238781f39a74496008aeb8be76a7c700ad6e79eb8ec598295eb673

test:
  secret_key_base: 3c62f7055e2c0b00c6b1eac03038f548e7b77a373e21ecf62c0baecef1d7975f44bf3bd32a4f772d348f1392cc84c40202573e8eca0dcfdb1ab3eb531b4e3eff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
